### ISSUE TITLE
Option to output zero on exit

### ISSUE THREAD

**Issue by rckok** [RandomStudio/tether-artnet-controller#6]
When this application exits, the destination devices retain their last received values, meaning the lights stay on.
If the app crashes for whatever reason, it can be tricky to power down the lights. Aside from this, people using it to manually set the lights will likely more often than not neglect to manually set everything to its off state before exiting and leaving.

I would suggest to add an option (maybe even as default behavior with an option to disable) to output all zeroes to all channels upon application exit.

**Comment by anselanza** [comment]
This is implemented in v0.3.2. When closing the application (either in "headless" mode or with the GUI), the application will do the following before final exit:

- Save any currently-loaded project file automatically
- Set all light fixtures to "home" (default) positions/settings and send this via ArtNet
- Allow worker threads (just Tether interface for now) to end properly
-
